/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        brand: '#6c3bfe',
        'brand-light': '#f1f0fe',
        'brand-mid': '#ede9fe',
        surface: '#ffffff',
        'surface-raised': '#f8fafc',
        border: '#eef1f7',
        'border-hover': '#d1d9e8',
        'text-primary': '#0f172a',
        'text-secondary': '#64748b',
        'text-muted': '#94a3b8',
        'green-bg': '#f0fdf4',
        'green-text': '#16a34a',
        'green-dot': '#22c55e',
        'pink-bg': '#fdf2f8',
        'pink-text': '#a21caf',
        'blue-bg': '#eff6ff',
        'blue-text': '#1d4ed8',
        'orange-bg': '#fff7ed',
        'orange-text': '#c2410c',
        'purple-bg': '#faf5ff',
        'purple-text': '#7e22ce',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      borderRadius: {
        sm: '5px',
        md: '7px',
        lg: '10px',
        xl: '14px',
      },
      spacing: {
        4: '4px',
        8: '8px',
        12: '12px',
        16: '16px',
        20: '20px',
        24: '24px',
        32: '32px',
        40: '40px',
        48: '48px',
        64: '64px',
      },
    },
  },
  plugins: [],
}
